---
name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Multi-hop SSH to target via two jumps
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SSH_PROXY_HOST }}         # jumphost
        username: ${{ secrets.SSH_PROXY_USERNAME }}
        key: ${{ secrets.SSH_PROXY_PRIVATE_KEY }}
        script: |
          ssh -o StrictHostKeyChecking=no \
              -i ~/.ssh/internal_key \
              -J ${{ secrets.INTERNAL_USER }}@${{ secrets.INTERNAL_HOST }} \
              ${{ secrets.TARGET_USER }}@${{ secrets.TARGET_HOST }} \
              "echo 'Connected to target host!'; hostname; ls -l /tmp"
