---
name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null
jobs:
  build:
    runs-on: semanticmatter
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Testing
      run: echo "Hello from semanticmatter"
