---
name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null
jobs:
  build:
    runs-on: semanticmatter
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Multi-hop SSH to target via two jumps
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SSH_PROXY_HOST }}         # jumphost
        username: ${{ secrets.SSH_PROXY_USERNAME }}
        key: ${{ secrets.SSH_PROXY_PRIVATE_KEY }}
        script: |
          echo "Hello from jumphost"
